// Generated by CoffeeScript 1.3.3

/*
Drop Chart is a plug-in intended to allow for sinple d3 charts to easily be put into any html system.
*/


(function() {
  var Chart, ChartFetcher;

  ChartFetcher = (function() {

    ChartFetcher.prototype.charts = [];

    function ChartFetcher() {
      var chart, _i, _len, _ref;
      this.raw_charts = this.fetchCharts();
      _ref = this.raw_charts;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        chart = _ref[_i];
        this.charts.push(new Chart(chart));
      }
      debugger;
    }

    ChartFetcher.prototype.fetchCharts = function() {
      return jQuery(".drop-chart");
    };

    return ChartFetcher;

  })();

  Chart = (function() {

    function Chart(raw) {
      this.raw = raw;
      this.type = jQuery(this.raw).attr('data-type');
      this.source = jQuery(this.raw).attr('data-source');
      this.fetchData();
    }

    Chart.prototype.fetchData = function() {
      return this.data = window[this.source];
    };

    return Chart;

  })();

  jQuery(document).ready(function() {
    return new ChartFetcher();
  });

}).call(this);
